apiVersion: v1
kind: ReplicationController
metadata:
    name: hello-rc
spec:
    replicas: 2
    selector:
        app: hello-world
    template:
        metadata:
            labels: 
              app: hello-world
        spec:
            containers:
            - name: hello-pod
              image: yeasy/simple-web:latest
              ports:
              - containerPort: 80

